-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "matchesPlayed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rating" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "wins" INTEGER NOT NULL DEFAULT 0;
